name: Release

on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: get postgres version
        run: |
          sudo service postgresql start
          PGVER=$(psql --version | grep -Po '(?<=psql \(PostgreSQL\) )[^;]+(?=\.\d \()')
          PGROUTING_VERSION=$(grep -Po '(?<=project\(PGROUTING VERSION )[^;]+' CMakeLists.txt)
          echo "PGVER=${PGVER}" >> $GITHUB_ENV
          echo "PGPORT=5432" >> $GITHUB_ENV
          echo "PGIS=3" >> $GITHUB_ENV
          echo "PGROUTING_VERSION=${PGROUTING_VERSION}" >> $GITHUB_ENV

      - name: Verify Tag Name
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          if [ "${TAG_NAME}" != "${PGROUTING_VERSION}" ]; then
            echo "Tag name should be v${PGROUTING_VERSION}"
            exit 1
          fi

      - name: Add PostgreSQL APT repository
        run: |
          sudo apt-get install curl ca-certificates gnupg
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ \
            $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libboost-graph-dev \
            postgresql-${PGVER} \
            postgresql-${PGVER}-postgis-${PGIS} \
            postgresql-${PGVER}-postgis-${PGIS}-scripts \
            postgresql-server-dev-${PGVER} \
            graphviz
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list

      - name: Configure
        run: |
          export PATH=/usr/lib/postgresql/${PGVER}/bin:$PATH
          mkdir build
          cd build
          cmake -DPOSTGRESQL_VERSION=${PGVER} -DCMAKE_BUILD_TYPE=Release -DWITH_DOC=ON .. -DES=ON ..

      - name: Build
        run: |
          cd build
          make -j 4
          sudo make install

      # - name: Test
      #   run: |
      #     sudo service postgresql start
      #     sudo -u postgres createdb -p ${PGPORT}  ___pgr___test___
      #     sudo -u postgres bash ./tools/testers/pg_prove_tests.sh postgres ${PGPORT}  Release

      - name: Download Assets
        run: |
          wget -c https://github.com/${{ github.repository }}/archive/${TAG_NAME}.zip
          wget -c https://github.com/${{ github.repository }}/archive/${TAG_NAME}.tar.gz

      - name: Make Attachments
        run: |
          cd build/doc

          cp -r html doc-v${PGROUTING_VERSION}-en-es
          tar -zcvf doc-v${PGROUTING_VERSION}-en-es.tar.gz doc-v${PGROUTING_VERSION}-en-es

          cp -r html doc-v${PGROUTING_VERSION}-en
          rm -rf doc-v${PGROUTING_VERSION}-en/es
          tar -zcvf doc-v${PGROUTING_VERSION}-en.tar.gz doc-v${PGROUTING_VERSION}-en

          cp -r html doc-v${PGROUTING_VERSION}-es
          rm -rf doc-v${PGROUTING_VERSION}-es/en
          perl -pi -e 's/en\/index.html/es\/index.html/g' doc-v${PGROUTING_VERSION}-es/index.html
          tar -zcvf doc-v${PGROUTING_VERSION}-es.tar.gz doc-v${PGROUTING_VERSION}-es

          cd ../..
          BODY=$(grep -Pzo "(?s)pgRouting ${ABCD//./\\.} Release Notes.*?(?=pgRouting .\..\.. Release Notes)" NEWS | tr '\0' '\n')
          BODY="${BODY}\n\n\nABCD\n\n**ABCD**"
          echo "BODY=${BODY}" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            build/doc/doc-v${PGROUTING_VERSION}-en-es.tar.gz
            build/doc/doc-v${PGROUTING_VERSION}-en.tar.gz
            build/doc/doc-v${PGROUTING_VERSION}-es.tar.gz
            ${{ github.event.repository.name }}-${TAG_NAME}.zip
            ${{ github.event.repository.name }}-${TAG_NAME}.tar.gz
          name: ${TAG_NAME}
          body: ${BODY}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
