name: TEMP

on:
  push:
    branches-ignore:
      - 'translations_*'


jobs:
  release:
    name: Temp
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
        run: |
          ls -al
          git checkout gh-pages
          ls -al

      - name: Checkout master
        uses: actions/checkout@v2
          with:
            ref: develop
        run: |
          ls -al
          git checkout develop
          ls -al
