name: Release

on:
  push:
    branches-ignore:
      - 'translations_*'


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false

    steps:
      - uses: actions/checkout@v2

      – name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Update Developers Documentation
        run: |
          ls -al
          git checkout gh-pages
          ls -al

      - name: Temp
        run: |
          ls -al
          git checkout master
          ls -al
