name: Test

on:
  push:
    branches-ignore:
      - 'translations_*'


jobs:
  release:
    name: Test
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Git status
        run: |
          git status
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          touch abcd
          git add abcd
          git commit -m "Adding abcd"
          git push origin add-actions-script
          touch another-file
          ls

      - name: Update Users Documentation
        run: |
          git checkout origin/gh-pages
          git checkout -b gh-pages
          git status
          touch tempfile
          git add tempfile
          git commit -m "Adding tempfile"
          git push origin gh-pages
          ls
