name: Build for Windows

on:
  push:
    branches-ignore:
      - 'gh-pages'

env:
  postgis_version: 3

jobs:
  build:
    name: Build
    runs-on: windows-latest

    strategy:
      matrix:
        pg_major: [11.13, 12.8, 13.4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install boost
        uses: MarkusJx/install-boost@v1.0.1
        id: install-boost
        with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here:
          # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
          boost_version: 1.73.0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Install PostgreSQL
        run: |
          curl https://get.enterprisedb.com/postgresql/postgresql-${{ matrix.pg_major }}-1-windows-x64-binaries.zip --output pgsql.zip
          Expand-Archive 'pgsql.zip' -Force
          echo ("POSTGRESQL_DIR=" + $(Get-Location)\pgsql\pgsql) >> $env:GITHUB_ENV
          $env:path += ";${{ env.POSTGRESQL_DIR }}\bin\"
          $env:path -split ";"
          initdb -D pgsql\data -U postgres
          pg_ctl -D pgsql\data start

      - name: Check Postgres running
        run: |
          pgsql\pgsql\bin\psql -U postgres -d postgres -c "SELECT version()"

      - name: List files
        run: |
          ls pgsql\pgsql
          ls pgsql\pgsql\bin
          ls pgsql\pgsql\include
          ls pgsql\pgsql\include\server

      - name: Get file content
        run: |
          Get-Content -Path .\pgsql\pgsql\include\server\c.h

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DPOSTGRESQL_BIN=${{ env.POSTGRESQL_DIR }}\bin -DPOSTGRESQL_INCLUDE_DIR="${{ env.POSTGRESQL_DIR }}\include;${{ env.POSTGRESQL_DIR }}\include\server" -G"Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DWITH_DOC=OFF ..
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

      - name: build
        run: |
          cd build
          msbuild PGROUTING.sln /target:Build /property:Configuration=Release
